baseURL = "https://www.kaels-kabbage.com/"
languageCode = "en-us"
title = "Kael's Kabbage"
theme = "sp-minimal"
paginate        = 10
googleAnalytics = "UA-122097969-1"
pygmentsCodeFences = true
pygmentsStyle = "native"
assetDir = "."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1

[permalinks]
posts = "post/:slug"
renders = "render/:slug"

[params]
  title       = "Kael's Kabbage"
  subtitle    = "Tech Superfood"
  description = "Cabbage is awful, but this blog isn't :)"
  copyright   = "Kael Larkin 2018"
  authorImage = "Cabbage.png"
  email       = "kael.larkin@readify.net"

  #"single" or "multi"
  renderType = "multi"
  #"simple" or "original"
  themeStyle = "simple"

  googleAnalytics = "UA-122097969-1"

  name = "Kael Larkin"
  pageNotFoundTitle = "Uh oh, that page wasn't found!"
  kabbage = "https://www.kaels-kabbage.com/img/Cabbage.png"