baseURL = "https://www.kaels-kabbage.com/"
languageCode = "en-us"
title = "Kael's Kabbage"
pygmentsCodeFences = true
pygmentsStyle = "native"
assetDir = "."
timeout = "120s"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1

[params]
  title       = "Kael's Kabbage"
  subtitle    = "Tech Superfood"
  description = "Cabbage is awful, but this blog isn't :)"
  copyright   = "Kael Larkin 2018"
  authorImage = "Cabbage.webp"
  email       = "kael.larkin@outlook.com"

  #"single" or "multi"
  renderType = "multi"
  #"simple" or "original"
  themeStyle = "simple"


  name = "Kael Larkin"
  pageNotFoundTitle = "Uh oh, that page wasn't found!"
  kabbage = "https://www.kaels-kabbage.com/img/Cabbage.webp"