baseURL = "https://kaels-kabbage.com/"
languageCode = "en-us"
title = "Kael's Kabbage"
theme = "sp-minimal"
paginate        = 10
googleAnalytics = "UA-122097969-1"

[params]
  title       = "Kaels's Kabbage"
  subtitle    = "Tech Superfood"
  description = ""
  copyright   = "Kael Larkin 2018"
  authorImage = "Cabbage.webp"

  #"single" or "multi"
  renderType = "multi"
  #"simple" or "original"
  themeStyle = "simple"

  googleAnalytics = "UA-122097969-1"

  name = "Kael Larkin"
  pageNotFoundTitle = "Uh oh, that page wasn't found!"